[package]
name = "channel"
version = "0.1.0"
authors = ["tim-lange1 <t.lange.ext@studing.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
